name:                lab3-interpolation
version:             0.1.0.0

dependencies:
- base >= 4.7

library:
  source-dirs: src

executables:
  lab3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab3-interpolation

tests:
  lab3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab3-interpolation
    - hspec
    - QuickCheck